CREATE TABLE IF NOT EXISTS products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(120) NOT NULL,
  category VARCHAR(30) NOT NULL CHECK (category IN ('coffee','tea','food')),
  description VARCHAR(500) NOT NULL DEFAULT '',
  price BIGINT NOT NULL CHECK (price BETWEEN 1000 AND 100000000),
  stock INTEGER NOT NULL DEFAULT 0 CHECK (stock >= 0),
  active BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS orders (
  id UUID PRIMARY KEY,
  request_key UUID NOT NULL UNIQUE,
  customer_name VARCHAR(100) NOT NULL,
  phone VARCHAR(20) NOT NULL,
  address VARCHAR(400) NOT NULL,
  note VARCHAR(500) NOT NULL DEFAULT '',
  payment_method VARCHAR(20) NOT NULL CHECK (payment_method IN ('cash','bank')),
  payment_status VARCHAR(20) NOT NULL DEFAULT 'unpaid' CHECK (payment_status IN ('unpaid','paid','refunded')),
  status VARCHAR(20) NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','confirmed','preparing','completed','cancelled')),
  total BIGINT NOT NULL CHECK (total >= 0),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS order_items (
  order_id UUID NOT NULL REFERENCES orders(id),
  product_id BIGINT NOT NULL REFERENCES products(id),
  name VARCHAR(120) NOT NULL,
  unit_price BIGINT NOT NULL CHECK (unit_price > 0),
  quantity INTEGER NOT NULL CHECK (quantity BETWEEN 1 AND 100),
  PRIMARY KEY (order_id, product_id)
);
CREATE INDEX IF NOT EXISTS orders_created_idx ON orders(created_at DESC);
CREATE TABLE IF NOT EXISTS order_events (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  order_id UUID NOT NULL REFERENCES orders(id),
  description VARCHAR(200) NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
INSERT INTO products(name,category,description,price,stock)
SELECT v.* FROM (VALUES
 ('Cà phê sữa đá','coffee','Cà phê đậm vị, sữa đặc và đá mát lạnh.',25000::BIGINT,40),
 ('Cappuccino','coffee','Espresso, sữa nóng và lớp bọt sữa mịn.',35000::BIGINT,30),
 ('Latte','coffee','Êm dịu, thơm cà phê và ngọt nhẹ vị sữa.',35000::BIGINT,30),
 ('Cold brew','coffee','Ủ lạnh chậm, thanh mát và ít đắng.',40000::BIGINT,25),
 ('Trà đào cam sả','tea','Trà thơm, đào giòn cùng cam và sả.',35000::BIGINT,30),
 ('Trà chanh','tea','Một chút chua dịu cho ngày nắng.',25000::BIGINT,35),
 ('Croissant bơ','food','Bánh ngàn lớp thơm bơ, nướng vàng.',28000::BIGINT,20),
 ('Bánh chocolate','food','Chocolate đậm vị, mềm và vừa ngọt.',32000::BIGINT,15)
) AS v(name,category,description,price,stock)
WHERE NOT EXISTS (SELECT 1 FROM products);
